### ISSUE TITLE
please update laravel 7

### ISSUE THREAD

**Issue by Gellish** [Codexshaper/laravel-database-manager#9]

**Comment by Codexshaper** [comment]
Hello @Gellish,

What's the error? I think codes are up to date and it works for laravel 7. 

If you face any issue please share screenshot or send details.

**Comment by maab16** [comment]
Hello @Gellish,

Thanks for creating an issue. I think it's conflict with illuminate support. BTW I release new version v1.2 . Please try new version.

**Comment by Gellish** [comment]
> Hello @Gellish,
> 
> What's the error? I think codes are up to date and it works for laravel 7.
> 
> If you face any issue please share screenshot or send details.

Problem 1
    - The requested package guzzlehttp/guzzle (locked at 6.5.5, required as ^7.0) is satisfiable by guzzlehttp/guzzle[6.5.5] but these conflict with your requirements or minimum-stability.

composer.json
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["laravel", "nuxt", "vue", "spa"],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0",
        "ipinfo/ipinfo": "^1.1",
        "laravel/framework": "^7.0",
        "laravel/passport": "^9.3",
        "laravel/socialite": "^4.3",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "predis/predis": "^1.1",
        "realrashid/sweet-alert": "^3.1",
        "symfony/psr-http-message-bridge": "^2.0",
        "tymon/jwt-auth": "^1.0.0-rc.5"
    },
i think the problem is   "guzzlehttp/guzzle": "^7.0", i wish support this version

**Comment by maab16** [comment]
laravel-database-manager doesn't need guzzlehttp/guzzle by default and this error is guzzlehttp related. I think "guzzlehttp/guzzle": "^6.3", is satisfiable with laravel 7.

Try this package in installation and inform me it works or not. Then you can configure the error easily. Don't worry I'm there to help you.

**Comment by Gellish** [comment]
> laravel-database-manager doesn't need guzzlehttp/guzzle by default and this error is guzzlehttp related. I think "guzzlehttp/guzzle": "^6.3", is satisfiable with laravel 7.
> 
> Try this package in installation and inform me it works or not. Then you can configure the error easily. Don't worry I'm there to help you.

 "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["laravel", "nuxt", "vue", "spa"],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "6.3",
        "ipinfo/ipinfo": "^1.1",
        "laravel/framework": "^7.0",
        "laravel/passport": "^8.0",
        "laravel/socialite": "^4.3",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "predis/predis": "^1.1",
        "realrashid/sweet-alert": "^3.1",
        "symfony/psr-http-message-bridge": "^1.0",
        "symfony/http-foundation": "^3.4",
        "tymon/jwt-auth": "^1.0.0-rc.5"
    },

"guzzlehttp/guzzle": "^6.3", is satisfiable with laravel 7. it;s ok now but its getting worse I'm triying installing

λ composer require symfony/http-foundation ^3.4.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package laravel/passport (locked at v9.3.0, required as ^8.0) is satisfiable by laravel/passport[v9.3.0] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package symfony/psr-http-message-bridge (locked at v2.0.1, required as ^1.0) is satisfiable by symfony/psr-http-message-bridge[v2.0.1] but these conflict with your requirements or minimum-stability.
  Problem 3
    - laravel/framework v7.19.0 requires symfony/http-foundation ^5.0 -> satisfiable by symfony/http-foundation[5.0.x-dev, 5.1.x-dev, 5.2.x-dev].
    - laravel/framework v7.19.0 requires symfony/http-foundation ^5.0 -> satisfiable by symfony/http-foundation[5.0.x-dev, 5.1.x-dev, 5.2.x-dev].
    - laravel/framework v7.19.0 requires symfony/http-foundation ^5.0 -> satisfiable by symfony/http-foundation[5.0.x-dev, 5.1.x-dev, 5.2.x-dev].
    - Can only install one of: symfony/http-foundation[v3.4.0, 5.0.x-dev].
    - Can only install one of: symfony/http-foundation[v3.4.0, 5.1.x-dev].
    - Can only install one of: symfony/http-foundation[v3.4.0, 5.2.x-dev].
    - Installation request for symfony/http-foundation 3.4.0 -> satisfiable by symfony/http-foundation[v3.4.0].
    - Installation request for laravel/framework (locked at v7.19.0, required as ^7.0) -> satisfiable by laravel/framework[v7.19.0].


Installation failed, reverting ./composer.json to its original content.
